name: Publish Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'helm/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Configure Git
        run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Package Helm Chart
        run: |
          mkdir -p .cr-release-packages
          helm package helm/app-chart -d .cr-release-packages

      - name: Create or Update gh-pages branch
        run: |
          git checkout gh-pages || git checkout -b gh-pages
          cp -r .cr-release-packages/* .
          helm repo index . --url https://${{ github.repository_owner }}.github.io/helm-charts
          git add .
          git commit -m "Update Helm chart repository" || echo "No changes to commit"
          git push origin gh-pages 
